version: 2.1
orbs:
  yarn: itinerisltd/yarn@2.1.1
jobs:
  build:
    docker:
      - image: cimg/node:18.14.1
    working_directory: ~/sylo-ethereum-contracts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn install
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: build contracts
          command: yarn build
      - run:
          name: solidity lint
          command: yarn solhint
      - run:
          name: prepare artifacts
          command: npx ts-node scripts/parse_artifacts.ts
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/sylo-ethereum-contracts

  test-node:
    docker:
      - image: circleci/node:16
    working_directory: ~/sylo-ethereum-contracts
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: test contracts
          command: ITERATIONS=10000 npm test
      - run:
          name: prepare outputs
          command: npx ts-node scripts/parse_artifacts.ts
      - store_artifacts:
          path: ~/sylo-ethereum-contracts/gasReport.txt

  test-coverage:
    docker:
      - image: circleci/node:16
    working_directory: ~/sylo-ethereum-contracts
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: test contracts
          command: yarn coverage
      - store_artifacts:
          path: ~/sylo-ethereum-contracts/coverage

workflows:
  build-and-test:
    jobs:
      - build
      - test-node:
          requires:
            - build
      - test-coverage:
          requires:
            - test-node
  version: 2
