version: 2

jobs:
  build:
    docker:
      - image: circleci/node:17
    working_directory: ~/sylo-ethereum-contracts
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm-install
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build contracts
          command: npm run build
      - run:
          name: solidity lint
          command: npm run solhint
      - run:
          name: prepare outputs
          command: node ./scripts/parseArtifacts.js
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/sylo-ethereum-contracts

  test-node:
    docker:
      - image: circleci/node:16
    working_directory: ~/sylo-ethereum-contracts
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: test contracts
          command: ITERATIONS=10000 npm test
      - run:
          name: prepare outputs
          command: node ./scripts/parseArtifacts.js
      - store_artifacts:
          path: ~/sylo-ethereum-contracts/gasReport.txt

  test-coverage:
    docker:
      - image: circleci/node:16
    working_directory: ~/sylo-ethereum-contracts
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: |
          npm run coverage
          npx sc-istanbul check-coverage --statements 100 --branches 100 --functions 100 --lines 100
      - store_artifacts:
            path: ~/sylo-ethereum-contracts/coverage

workflows:
  build-and-test:
    jobs:
      - build
      - test-node:
          requires:
            - build
      - test-coverage:
          requires:
            - test-node
  version: 2
