name: Push Docker image
on:
  push:
    tags:
      - v*.*.**

jobs:
  build-and-push-seeker-image:
    name: Build Docker image for local ganache network
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Tag and Push Docker image
        uses: docker/build-push-action@v5
        with:
          file: docker/ganache-with-protocol/Dockerfile
          tags: dn3010/sylo-ethereum-testnet:ganache
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
