name: Run gosec
on: pull_request

permissions:
  contents: read

jobs:
  tests:
    name: security check
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/dn3010
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DN3010_CI_SSH_KEY }}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DN3010_CI_SSH_KEY }}
          known_hosts: github.com/dn3010
      - name: Run gosec Security Scanner
        run: |
          git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
          cd go-eth
          go get -d ./...
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s v2.8.0
          ./bin/gosec ./... -exclude-dir contracts
